### ISSUE TITLE
Add integration with itazuraneko

### ISSUE THREAD

**Issue by Helmasko** [max-kamps/jpd-breader#29]
As the title says it, add support for the novel section of itzuranekko like for the ttsu app.
Right now when you try selecting all the text to parse, you either get: text too long, Error: Cannot read properties of undefined (reading 'parentNode'), or I remember getting something about reaching end of document.

**Comment by max-kamps** [comment]
These bugs with the right click selection parsing should be fixed now, hopefully :+1:

Currently I don't think I'll be adding integration for Itazuraneko. For the full reasoning, you can see the pull request from mikzorz, but TL;DR Integrations should only be used for websites that actually need it (IMO), rather than for avoiding bugs, and I also don't want to add integrations for piracy websites.
